<?xml version="1.0" encoding="utf-8"?><Database Name="OriginXDB" Class="OriginXLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RANGANATH;Initial Catalog=OriginXDB;Integrated Security=True" SettingsObjectName="OrginxDataService.Properties.Settings" SettingsPropertyName="OriginXDBConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.addemployees" Method="addemployees">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="user_level" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addCustomer" Method="addCustomer">
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>